version: "3.9"

networks:
  apps:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - apps
    deploy:
      placement:
        constraints:
          - node.hostname == ${CORE_HOSTNAME}
