version: "3.9"

name: cloudflared

networks:
  dns:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
