version: "3.9"

networks:
  apps:
    external: true

services:
  caddy:
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ${BASE_FAST_DIR}/caddy/etc:/etc/caddy
      - ${BASE_FAST_DIR}/caddy/data:/data
      - ${BASE_FAST_DIR}/caddy/config:/config
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    hostname: caddy
    networks:
      - apps
    environment:
      CF_API_TOKEN: ${CLOUDFLARE_TOKEN}
    deploy:
      placement:
        constraints:
          - node.hostname == ${CORE_HOSTNAME}
