version: "3.9"

networks:
  mongodb:
    external: true

services:
  mongo:
    image: mongo:8
    hostname: mongo
    networks:
      - mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    user: root
    volumes:
      - ${BASE_FAST_DIR}/mongodb/db:/data/db
      - ${BASE_FAST_DIR}/mongodb/config:/data/configdb
    deploy: 
      placement:
        constraints:
          - node.hostname == ${CORE_HOSTNAME}
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password example --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
