version: "3.9"

networks:
  mongodb:
    external: true
  prometheus:
    external: true

services:
  mongo:
    image: mongo:8
    hostname: mongo
    networks:
      - mongodb
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    user: root
    volumes:
      - /root/homelab/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ${BASE_FAST_DIR}/mongodb/db:/data/db
      - ${BASE_FAST_DIR}/mongodb/config:/data/configdb
    deploy: 
      placement:
        constraints:
          - node.hostname == ${CORE_HOSTNAME}
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password ${MONGO_ROOT_PASSWORD} --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  mongodb-exporter:
    image: docker.io/percona/mongodb_exporter:${MONGODB_EXPORTER_VERSION:-0.44.0}
    hostname: mongo-exporter
    networks:
      - mongodb
    depends_on:
      - mongo
    command:
      - --mongodb.uri=mongodb://root:${MONGO_ROOT_PASSWORD_ESCAPED}@mongodb:27017/?
      - --collect-all
      - --compatible-mode

