---

services:
  postgresql:
  server:
    image: ghcr.io/goauthentik/server:2025.6.4
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASS}
    volumes:
      - ${BASE_FAST_DIR}/authentik/media:/media
      - ${BASE_FAST_DIR}/authentik/templates:/templates
  worker:
    image: ghcr.io/goauthentik/server:2025.6.4
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_FAST_DIR}/authentik/media:/media
      - ${BASE_FAST_DIR}/authentik/certs:/certs
      - ${BASE_FAST_DIR}/authentik/templates:/templates
