version: "3.9"

networks:
  apps:
    external: true
  redis:
    external: true

services:
  self-service-password:
    image: ltbproject/self-service-password:dev-master
    hostname: self-service
    networks:
      - apps
      - redis
    user: root
    volumes:
      - ${BASE_FAST_DIR}/ad-self-service/config:/var/www/conf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy: 
      placement:
        constraints:
          - node.hostname == ${CORE_HOSTNAME}
