version: "3.9"

networks:
  apps:
    external: true

services:
  self-service-password:
    image: ltbproject/self-service-password:dev-master
    hostname: self-service
    networks:
      - apps
    user: root
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Manila
      JELLYFIN_PublishedServerUrl: "${JELLYFIN_PUBLIC_URL}"
    volumes:
      - ${BASE_FAST_DIR}/jellyfin/config:/config
      - ${BASE_SLOW_DIR}${MEDIA_TVSHOW_PATH}:/data/tvshows
      - ${BASE_SLOW_DIR}${MEDIA_MOVIES_PATH}:/data/movies
      - ${BASE_SLOW_DIR}${MEDIA_MUSIC_PATH}:/data/music
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy: 
      placement:
        constraints:
          - node.hostname == ${APPS_HOSTNAME}
