version: "3.9"

networks:
  apps:
    external: true
  postgres:
    external: true

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    hostname: jellyseerr
    networks:
      - apps
      - postgres
    user: root
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Manila
      - DB_TYPE=postgres
      - DB_HOST="postgres.postgres"
      - DB_USER=jellyseerr 
      - DB_PASS=${JELLYSEERR_PG_PASS}
      - DB_NAME="jellyseerr"
    volumes:
      - ${BASE_FAST_DIR}/jellyseerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    deploy: 
      placement:
        constraints:
          - node.hostname == ${APPS_HOSTNAME}
