version: "3.9"

networks:
  apps:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    hostname: qbittorrent
    networks:
      - apps
    user: root
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Manila
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${BASE_FAST_DIR}/qbit/config:/config
      - ${BASE_SLOW_DIR}${DOWNLOADER_PATH}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v2/app/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy: 
      placement:
        constraints:
          - node.hostname == ${APPS_HOSTNAME}
