version: "3.9"

networks:
  apps:
    external: true
  postgres:
    external: true

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:12
    hostname: forgejo
    networks:
      - apps
      - postgres
    user: root
    environment:
      USER_UID: 1000
      USER_GID: 1000
      TZ: Asia/Manila
      FORGEJO__server__DOMAIN: ${FORGEJO_DOMAIN}
      FORGEJO__server__DISABLE_SSH: 'true'
      FORGEJO__server__ROOTURL: https://${FORGEJO_DOMAIN}/
      FORGEJO__service__DISABLE_REGISTRATION: 'true'
      FORGEJO_openid__ENABLE_OPENID_SIGNIN: false
      FORGEJO_openid__ENABLE_OPENID_SIGNUP: false
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: postgres.postgres:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: ${FORGEJO_PG_PASS}

    volumes:
      - ${BASE_FAST_DIR}/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy: 
      placement:
        constraints:
          - node.hostname == ${APPS_HOSTNAME}
