version: "3.9"

networks:
  apps:
    external: true
  redis:
    external: true
  mongo:
    external: true

services:
  sharelatex:
    image: sharelatex/sharelatex:latest
    hostname: "overleaf"
    networks: 
      - apps
      - mongo
      - redis
    environment:
      TZ: 'Asia/Manila'
      REDIS_HOST: "redis.redis"
      REDIS_PORT: "6379"
      OVERLEAF_LISTEN_IP: "0.0.0.0"
      OVERLEAF_APP_NAME: "Rinaldo's Math Lab"
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "false"
      OVERLEAF_SITE_URL: "https://overleaf.rinaldolee.com"
      OVERLEAF_NAV_TITLE: "Rinaldo's Math Lab"
      #OVERLEAF_HEADER_IMAGE_URL: "http://somewhere.com/mylogo.png"
      OVERLEAF_ADMIN_EMAIL: "rinaldochenglee@gmail.com"
      OVERLEAF_LEFT_FOOTER: '[{"text": "Contact the host", "url": "mailto:${SMTP_USER}"}]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": ""}]'
      OVERLEAF_EMAIL_FROM_ADDRESS:  "${SMTP_USER}"
      OVERLEAF_EMAIL_SMTP_HOST: "smtp.gmail.com"
      OVERLEAF_EMAIL_SMTP_PORT: 465
      OVERLEAF_EMAIL_SMTP_SECURE: "true"
      OVERLEAF_EMAIL_SMTP_USER: "${SMTP_USER}"
      OVERLEAF_EMAIL_SMTP_PASS: "${SMTP_PASSWORD}"
      #OVERLEAF_EMAIL_SMTP_NAME: "Rinaldo Lee"
      OVERLEAF_EMAIL_SMTP_LOGGER: "true"
      OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: "true"
      OVERLEAF_EMAIL_SMTP_IGNORE_TLS: "false"
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This Overleaf instance is run by Rinaldo Lee"
      OVERLEAF_MONGO_URL: "mongodb://overleaf:OVERLEAF_MONGO_PASSWORD_ESCAPED@mongo.mongo:27017/overleaf?authSource=admin"
    user: root
    # Volumes store your data between container upgrades
    volumes:
      - "${BASE_FAST_DIR}/overleaf:/var/lib/overleaf"
