version: "3.9"

networks:
  apps:
    external: true

services:
  drawio:
    image: jgraph/drawio
    hostname: "drawio"
    stdin_open: true
    tty: true
    networks: 
      - apps
    user: root
    deploy: 
      placement:
        constraints:
          - node.hostname == ${APPS_HOSTNAME}
